DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;
 
CREATE TABLE USERS (
  	id INT AUTO_INCREMENT  PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	last_name VARCHAR(250)DEFAULT NULL,
	email VARCHAR(250) DEFAULT NULL,	
	enabled BOOLEAN DEFAULT true,	
	password VARCHAR(250) DEFAULT NULL);
	
	CREATE TABLE ROLES (
  	id INT AUTO_INCREMENT  PRIMARY KEY,
	role_name VARCHAR(250) NOT NULL);
	
	CREATE TABLE USERS_ROLES (
	user_id int ,
	role_id int);